# backend/Dockerfile
FROM node:22-alpine

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm ci

# Copiar código
COPY . .

# Build (si usás dist)
RUN npm run build

ENV NODE_ENV=production
EXPOSE 10000

# Render define PORT. Tu app debe usar process.env.PORT.
CMD ["node", "dist/main.js"]
